package com.newphone.newphonemodulo.ui.config;

public class FieldConfig {

    private final String name;
    private final String label;
    private final FieldType type;
    private final boolean primaryKey;
    private final boolean autoGenerated;

    public FieldConfig(String name, String label, FieldType type, boolean primaryKey, boolean autoGenerated) {
        this.name = name;
        this.label = label;
        this.type = type;
        this.primaryKey = primaryKey;
        this.autoGenerated = autoGenerated;
    }

    public FieldConfig(String name, String label, FieldType type) {
        this(name, label, type, false, false);
    }

    public String getName() {
        return name;
    }

    public String getLabel() {
        return label;
    }

    public FieldType getType() {
        return type;
    }

    public boolean isPrimaryKey() {
        return primaryKey;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
}
